version: "3.9"
services:
  test:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 0
              capabilities: [gpu]
    ports:
      - "4444:8888"
      - "6464:4646"
      - "1818:8181"
      - "7777:22"
    volumes:
      - /mnt/data/defilippis/:/opt/data/